"""Initial Migration3

Revision ID: 150be70fb2d3
Revises: 7a2c6582f42d
Create Date: 2021-11-10 16:54:09.362991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '150be70fb2d3'
down_revision = '7a2c6582f42d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_pic_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic_path')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
